Repository JuliaDocs/DocStringExtensions.jl, pull requests merged in 2018-07, with the labels that each got.

#60 Use Core.eval instead of eval
  src/templates.jl
  src/utilities.jl
  test/tests.jl
Labels: Type: Maintenance

#61 Add 0.7 CI targets
  .travis.yml
  appveyor.yml
Labels: Type: Maintenance, Type: Tests

#62 Backports for 0.4.5
  .travis.yml
  appveyor.yml
  src/templates.jl
  src/utilities.jl
  test/tests.jl
Labels: Type: Backport
