Repository JuliaDocs/DocStringExtensions.jl, pull requests merged in 2019-06, with the labels that each got.

#77 Add TYPEDFIELDS to display field names
  src/DocStringExtensions.jl
  src/abbreviations.jl
  test/tests.jl
Labels: Type: Feature

#78 Add showcase page to manual
  docs/Showcase/README.md
  docs/Showcase/src/Showcase.jl
  docs/make.jl
  docs/src/showcase.md
Labels: Type: Documentation

#79 Set version to 0.8.0
  Project.toml
  REQUIRE
Labels: Type: Maintenance

#80 Put an upper bound on compat Julia version
  Project.toml
Labels: Type: Maintenance

#81 Add analytics ID
  docs/make.jl
Labels: Type: Documentation
