Repository JuliaDocs/DocStringExtensions.jl, pull requests merged in 2020-06, with the labels that each got.

#88 Fix typed signatures parametric types
  docs/Showcase/src/Showcase.jl
  docs/src/showcase.md
  src/abbreviations.jl
  src/utilities.jl
  test/TestModule/M.jl
  test/tests.jl
Labels: Type: Bug

#91 Use underscore for unnamed arguments
  src/utilities.jl
  test/tests.jl
Labels: Type: Enhancement

#90 Set version to 0.8.2
  Project.toml
Labels: Type: Maintenance
